import React from 'react';
import CredibilityBar from './CredibilityBar';
import BiasBadge from './BiasBadge';
import LabelTags from './LabelTags';

const ResultsDisplay = ({ results }) => {
  const { source, credibility_score, bias, summary, labels, metadata } = results;

  return (
    <div className="bg-white rounded-lg shadow-lg overflow-hidden">
      {/* Header */}
      <div className="bg-gradient-to-r from-blue-600 to-indigo-600 text-white p-6">
        <h2 className="text-2xl font-bold mb-2">Analysis Results</h2>
        <div className="flex items-center justify-between">
          <span className="text-blue-100">Source: {source}</span>
          <BiasBadge bias={bias} />
        </div>
      </div>

      <div className="p-6 space-y-6">
        {/* Article Title */}
        {metadata?.title && (
          <div>
            <h3 className="text-lg font-semibold text-gray-800 mb-2">Article Title</h3>
            <p className="text-gray-700 leading-relaxed">{metadata.title}</p>
          </div>
        )}

        {/* Summary */}
        <div>
          <h3 className="text-lg font-semibold text-gray-800 mb-2">Summary</h3>
          <div className="bg-gray-50 rounded-lg p-4">
            <p className="text-gray-700 leading-relaxed">{summary}</p>
          </div>
        </div>

        {/* Credibility Score */}
        <div>
          <h3 className="text-lg font-semibold text-gray-800 mb-3">Credibility Score</h3>
          <CredibilityBar score={credibility_score} />
        </div>

        {/* Labels */}
        {labels && labels.length > 0 && (
          <div>
            <h3 className="text-lg font-semibold text-gray-800 mb-3">Analysis Labels</h3>
            <LabelTags labels={labels} />
          </div>
        )}

        {/* Additional Metadata */}
        <div className="border-t pt-4">
          <h3 className="text-lg font-semibold text-gray-800 mb-3">Additional Information</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
            {metadata?.authors && (
              <div>
                <span className="font-medium text-gray-600">Authors:</span>
                <span className="ml-2 text-gray-700">{metadata.authors}</span>
              </div>
            )}
            {metadata?.publish_date && metadata.publish_date !== 'Unknown' && (
              <div>
                <span className="font-medium text-gray-600">Published:</span>
                <span className="ml-2 text-gray-700">
                  {new Date(metadata.publish_date).toLocaleDateString()}
                </span>
              </div>
            )}
            {metadata?.processing_time_seconds && (
              <div>
                <span className="font-medium text-gray-600">Processing Time:</span>
                <span className="ml-2 text-gray-700">{metadata.processing_time_seconds}s</span>
              </div>
            )}
            {metadata?.analysis_method && (
              <div>
                <span className="font-medium text-gray-600">Analysis Method:</span>
                <span className="ml-2 text-gray-700 capitalize">
                  {metadata.analysis_method.replace('_', ' ')}
                </span>
              </div>
            )}
          </div>
        </div>

        {/* Disclaimer */}
        <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
          <div className="flex items-start">
            <div className="flex-shrink-0">
              <svg className="w-5 h-5 text-yellow-400 mt-0.5" fill="currentColor" viewBox="0 0 20 20">
                <path fillRule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
              </svg>
            </div>
            <div className="ml-3">
              <p className="text-sm text-yellow-800">
                <strong>Disclaimer:</strong> This analysis is generated by AI models and should be used as a starting point for your own research. Always verify information from multiple sources before making decisions.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ResultsDisplay;